version: "3.9"
   
services:

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    environment:
      - POSTGRES_DB=talanddev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpass
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  graphql-engine:
      image: hasura/graphql-engine:v1.3.2
      ports:
      - "8080:8080"
      depends_on:
      - "postgres"
      restart: always
      environment:
        HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:secretpass@postgres:5432/postgres
        ## enable the console served by server
        HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
        ## enable debugging mode. It is recommended to disable this in production
        HASURA_GRAPHQL_DEV_MODE: "false"
        HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
        HASURA_GRAPHQL_ADMIN_SECRET: admin_secret